### ISSUE TITLE
main files are in the public folder

### ISSUE THREAD

**Issue by ghost** [ImaEntity/LunarOS#1]
heyo uh if i go to https://imaentity.github.io/LunarOS/ it nono work 😢
tis is because you are very smart and put the main files inside of the public folder which doesnt work with github pages 🤑
so like if i go to https://imaentity.github.io/LunarOS/public/ it lets me see that site but thats annoying 😡
so move the files out of the public folder and delete yo express server 😊

**Comment by ImaEntity** [comment]
That's a whole lotta work for a dead project
